== Academic Integrity

Copied and unattributed work will receive zero credit. At Bryn Mawr, we assume students are
trustworthy and work with honesty and integrity.
link:https://www.brynmawr.edu/deans/academic-and-community-integrity[Look here
for information about Bryn Mawr's Honor Code.] 

As you progress in this course, you will see that programming is a creative
process, similar to writing. The same problem can be solved in
multiple ways. It's _essential_ that you develop your own skills for developing
algorithms and implementing them through programs. 

Quizzes and exams will be _closed book_. You will be able to bring a 
single cheat sheet with you. *The goal of assignments and labs is to help you 
prepare for quizzes and exams!* If you can sit down, focus, and answer sample 
questions within a time limit, you will ace the exams for this class. 
Incidentally, you will also be prepared to ace a job interview on this topic! 

Integrity Guidelines: 

* DO discuss ideas and approaches with your classmates.
* DO discuss ideas and approaches with your TAs and instructor.
* DO search for documentation and sample programs for built-in C functions and C syntax.
* DO use code from our text books and class (with attribution).

* DON'T use Chat-GPT (or other LLMs) to generate solutions.
* DON'T copy full solutions, from online tutorials, previous students, etc
* DON'T use functions and C syntax that is disallowed by the Makefile. We are deliberately using simple and portable C.
* DON'T modify any basecode that comes with your assignment. 
* DON'T ever share your code with other students.

It's ultimately up to you to learn from your assignments! Remember, no one is
going to hire you to do work that they can easily do themselves using a search
or AI program generator. The programs in this course are simple enough for an AI
or search or two to solve. But the next level of programs will not be so simple. You must
do the work yourself. This is the only way you will develop the skills and
expertise to reach your full potential. 

One final point: we will be using open-source repositories for homeworks in this class. 
Thus, it will be possible to see what other students (and previous students) have submitted. 
If you copy from others' repositories, it will be obvious to everyone involved! Only look 
at other solutions after you have finished your own first!
